import assert from "node:assert/strict";
import test from "node:test";
import { decodeCursor, encodeCursor } from "./cursor.js";
import { ApiError } from "./errors.js";
import { parseAggregateQuery, parseLogsQuery, validateIngestionBatch } from "./validation.js";

test("accepts valid logs and reports invalid entries independently", () => {
  const result = validateIngestionBatch({ logs: [
    { timestamp: "2020-08-09T10:00:00Z", level: "info", service: "api", message: "started", attributes: { region: "eu", retries: 2 } },
    { timestamp: "2020-08-09T10:00:00Z", level: "critical", service: "api", message: "invalid" },
  ] });
  assert.equal(result.validLogs.length, 1);
  assert.deepEqual(result.rejected, [{ index: 1, reason: "invalid level: 'critical'" }]);
});

test("preserves arbitrary safe attribute keys and rejects values PostgreSQL cannot store", () => {
  const accepted = validateIngestionBatch(JSON.parse(`{"logs":[{
    "timestamp":"2020-08-09T10:00:00Z","level":"info","service":"api","message":"started",
    "attributes":{"__proto__":"kept","ordinary":"value"}
  }]}`));
  assert.equal(accepted.validLogs.length, 1);
  const acceptedLog = accepted.validLogs[0];
  assert.ok(acceptedLog);
  assert.ok(acceptedLog.attributes);
  assert.equal(Object.prototype.hasOwnProperty.call(acceptedLog.attributes, "__proto__"), true);
  assert.equal(acceptedLog.attributes.__proto__, "kept");

  const directFilter = parseLogsQuery({ "attr.__proto__": "kept" });
  const compoundFilter = parseLogsQuery({ query: "attr.__proto__:kept" });
  assert.equal(Object.prototype.hasOwnProperty.call(directFilter.attributes, "__proto__"), true);
  assert.equal(Object.prototype.hasOwnProperty.call(compoundFilter.attributes, "__proto__"), true);
  assert.equal(compoundFilter.attributes.__proto__, "kept");

  const rejected = validateIngestionBatch({ logs: [{
    timestamp: "2020-08-09T10:00:00Z", level: "info", service: "api\0", message: "started",
  }, {
    timestamp: "2020-08-09T10:00:00Z", level: "info", service: "api", message: "started",
    attributes: { region: "eu\0" },
  }, {
    timestamp: "2020-08-09T10:00:00Z", level: "info", service: "api", message: "started",
    attributes: { "": "unqueryable" },
  }] });
  assert.equal(rejected.validLogs.length, 0);
  assert.equal(rejected.rejected.length, 3);
  assert.throws(() => parseLogsQuery({ "attr.__proto__": "kept\0" }), ApiError);
});

test("cursor round trip preserves deterministic ordering fields", () => {
  const cursor = { timestamp: new Date("2026-08-09T10:00:00.000Z"), id: "00000000-0000-4000-8000-000000000001" };
  assert.deepEqual(decodeCursor(encodeCursor(cursor)), cursor);
});

test("cursor accepts UUIDv7 identifiers generated by the write path", () => {
  const cursor = { timestamp: new Date("2026-08-09T10:00:00.000Z"), id: "0198f7c0-8a00-7a12-8abc-0123456789ab" };
  assert.deepEqual(decodeCursor(encodeCursor(cursor)), cursor);
});

test("cursor preserves the internal selective-attribute pagination marker", () => {
  const cursor = {
    timestamp: new Date("2026-08-09T10:00:00.000Z"),
    id: "0198f7c0-8a00-7a12-8abc-0123456789ab",
    attributeCandidateMode: true as const,
  };
  assert.deepEqual(decodeCursor(encodeCursor(cursor)), cursor);
  const malformed = Buffer.from(JSON.stringify({
    timestamp: cursor.timestamp.toISOString(), id: cursor.id, attribute_candidate_mode: false,
  })).toString("base64url");
  assert.throws(() => decodeCursor(malformed), ApiError);
});

test("cursor preserves bounded attribute-page session state", () => {
  const cursor = {
    timestamp: new Date("2026-08-09T10:00:00.000Z"),
    id: "0198f7c0-8a00-7a12-8abc-0123456789ab",
    attributePageSession: {
      id: "00000000-0000-4000-8000-000000000001",
      offset: 100,
    },
  };
  assert.deepEqual(decodeCursor(encodeCursor(cursor)), cursor);
  const malformed = Buffer.from(JSON.stringify({
    timestamp: cursor.timestamp.toISOString(), id: cursor.id,
    attribute_page_session: { id: cursor.attributePageSession.id, offset: -1 },
  })).toString("base64url");
  assert.throws(() => decodeCursor(malformed), ApiError);
});

test("cursor preserves filter context when later pages omit query filters", () => {
  const cursor = encodeCursor({
    timestamp: new Date("2026-08-09T10:00:00.000Z"),
    id: "0198f7c0-8a00-7a12-8abc-0123456789ab",
    limit: 100,
    filterContext: {
      level: "error",
      service: "checkout",
      since: "2026-08-09T09:00:00.000Z",
      until: "2026-08-09T11:00:00.000Z",
      q: "declined",
      attributes: { request_id: "req-42" },
    },
  });
  const continued = parseLogsQuery({ cursor });
  assert.equal(continued.limit, 100);
  assert.equal(continued.level, "error");
  assert.equal(continued.service, "checkout");
  assert.equal(continued.since?.toISOString(), "2026-08-09T09:00:00.000Z");
  assert.equal(continued.until?.toISOString(), "2026-08-09T11:00:00.000Z");
  assert.equal(continued.q, "declined");
  assert.deepEqual(continued.attributes, { request_id: "req-42" });

  const repeated = parseLogsQuery({
    cursor,
    limit: "25",
    level: "error",
    service: "checkout",
    since: "2026-08-09T09:00:00.000Z",
    until: "2026-08-09T11:00:00.000Z",
    q: "declined",
    "attr.request_id": "req-42",
  });
  assert.equal(repeated.limit, 25);
  assert.equal(repeated.service, "checkout");
  assert.deepEqual(repeated.attributes, { request_id: "req-42" });

  const repeatedExpression = parseLogsQuery({
    cursor,
    query: "service:checkout level:error q:declined attr.request_id:req-42",
  });
  assert.equal(repeatedExpression.level, "error");
  assert.equal(repeatedExpression.service, "checkout");
  assert.equal(repeatedExpression.q, "declined");
  assert.deepEqual(repeatedExpression.attributes, { request_id: "req-42" });

  assert.throws(() => parseLogsQuery({ cursor, service: "auth" }), ApiError);
  assert.throws(() => parseLogsQuery({ cursor, "attr.request_id": "other" }), ApiError);
});

test("query parser validates filters and limits", () => {
  const result = parseLogsQuery({ limit: "25", level: "error", "attr.region": "eu", since: "2026-08-01T00:00:00Z" });
  assert.equal(result.limit, 25);
  assert.equal(result.level, "error");
  assert.equal(result.attributes.region, "eu");
});

test("query parser uses the maximum supported page size by default", () => {
  assert.equal(parseLogsQuery({}).limit, 10_000);
  assert.throws(() => parseLogsQuery({ limit: "10001" }), ApiError);
});

test("aggregation requires a time range and accepts the required 5m bucket", () => {
  assert.throws(() => parseAggregateQuery({ bucket: "1m" }), ApiError);
  const result = parseAggregateQuery({
    since: "2026-08-09T10:00:00Z",
    until: "2026-08-09T11:00:00Z",
    bucket: "5m",
    group_by: "service",
  });
  assert.equal(result.bucket, "5m");
  assert.equal(result.groupBy, "service");
});

test("rejects ISO-shaped timestamps with invalid calendar values", () => {
  const result = validateIngestionBatch({ logs: [
    { timestamp: "2026-02-30T10:00:00Z", level: "info", service: "api", message: "invalid date" },
    { timestamp: "2026-04-31T10:00:00Z", level: "info", service: "api", message: "invalid date" },
  ] });
  assert.equal(result.validLogs.length, 0);
  assert.equal(result.rejected.length, 2);
  assert.throws(() => parseLogsQuery({ since: "2026-02-30T10:00:00Z" }), ApiError);
});
